// <auto-generated />
namespace JiraIntegration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PI_Reporting_SnapshotSupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PI_Reporting_SnapshotSupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201601200538267_PI_Reporting_SnapshotSupport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
